define(function () {
    'use strict';
    return {
        'modules': [{
            'reconfig': true,
            'name': 'app.admin.states.adminAccountManager',
            'files': ['states/adminAccountManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.administratorManage',
            'files': ['states/administratorManage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.annualEstablish',
            'files': ['states/annualEstablish-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.areaPeriodLearnStatistic',
            'files': ['states/areaPeriodLearnStatistic-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.certifiedTemplate',
            'files': ['states/certifiedTemplate-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.channelDistribution',
            'files': ['states/channelDistribution-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.classEstablish',
            'files': ['states/classEstablish-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.classInformation',
            'files': ['states/classInformation-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.classLearning',
            'files': ['states/classLearning-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.courseCategoryManager',
            'files': ['states/courseCategoryManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.courseChooseStatistic',
            'files': ['states/courseChooseStatistic-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.courseManager',
            'files': ['states/courseManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.coursePackageManager',
            'files': ['states/coursePackageManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.coursePoolRuleManager',
            'files': ['states/coursePoolRuleManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.courseSelect',
            'files': ['states/courseSelect-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.coursewareAsyn',
            'files': ['states/coursewareAsyn-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.courseWareCategoryManager',
            'files': ['states/courseWareCategoryManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.courseWareManager',
            'files': ['states/courseWareManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.creditStatistics',
            'files': ['states/creditStatistics-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.defenceFakeLearning',
            'files': ['states/defenceFakeLearning-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.differentPrice',
            'files': ['states/differentPrice-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.distributionManager',
            'files': ['states/distributionManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.distributorOpenImportTask',
            'files': ['states/distributorOpenImportTask-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.distributorOpenManage',
            'files': ['states/distributorOpenManage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.distributorOrderManager',
            'files': ['states/distributorOrderManager-state']
        }, {'reconfig': true, 'name': 'app.admin.states.employee', 'files': ['states/employee-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.exam',
            'files': ['states/exam-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.examStatistics',
            'files': ['states/examStatistics-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.falseLearning',
            'files': ['states/falseLearning-state']
        }, {'reconfig': true, 'name': 'app.admin.states.feedback', 'files': ['states/feedback-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.goodsManager',
            'files': ['states/goodsManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.hasnotPopQuestionCourseList',
            'files': ['states/hasnotPopQuestionCourseList-state']
        }, {'reconfig': true, 'name': 'app.admin.states.home', 'files': ['states/home-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.humanActivation',
            'files': ['states/humanActivation-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.importClassOpen',
            'files': ['states/importClassOpen-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.importOpenClassTask',
            'files': ['states/importOpenClassTask-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.importStudent',
            'files': ['states/importStudent-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.importStudentTask',
            'files': ['states/importStudentTask-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.infoCategory',
            'files': ['states/infoCategory-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.infoContent',
            'files': ['states/infoContent-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.invoiceExport',
            'files': ['states/invoiceExport-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.invoiceManage',
            'files': ['states/invoiceManage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.invoiceViews',
            'files': ['states/invoiceViews-state']
        }, {'reconfig': true, 'name': 'app.admin.states.job', 'files': ['states/job-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.learningTimeStatistic',
            'files': ['states/learningTimeStatistic-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.logonStatistic',
            'files': ['states/logonStatistic-state']
        }, {'reconfig': true, 'name': 'app.admin.states.menu1', 'files': ['states/menu1-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.merchant',
            'files': ['states/merchant-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.messageReply',
            'files': ['states/messageReply-state']
        }, {'reconfig': true, 'name': 'app.admin.states.normal', 'files': ['states/normal-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.noticeManage',
            'files': ['states/noticeManage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.openRecord',
            'files': ['states/openRecord-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.orderAsynchExport',
            'files': ['states/orderAsynchExport-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.orderManage',
            'files': ['states/orderManage-state']
        }, {'reconfig': true, 'name': 'app.admin.states.orgManage', 'files': ['states/orgManage-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.packageDispatch',
            'files': ['states/packageDispatch-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.packageExportManager',
            'files': ['states/packageExportManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.packageImportManager',
            'files': ['states/packageImportManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.paperClassification',
            'files': ['states/paperClassification-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.paperConfig',
            'files': ['states/paperConfig-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.paymentAccount',
            'files': ['states/paymentAccount-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.periodSellStatistic',
            'files': ['states/periodSellStatistic-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.personCenter',
            'files': ['states/personCenter-state']
        }, {'reconfig': true, 'name': 'app.admin.states.player', 'files': ['states/player-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.popQuestionManager',
            'files': ['states/popQuestionManager-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.practicePaperConfig',
            'files': ['states/practicePaperConfig-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.problemCategory',
            'files': ['states/problemCategory-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.questionImport',
            'files': ['states/questionImport-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.questionLibrary',
            'files': ['states/questionLibrary-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.questionManage',
            'files': ['states/questionManage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.reconciliationManage',
            'files': ['states/reconciliationManage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.reconciliationViews',
            'files': ['states/reconciliationViews-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.refundAsynExport',
            'files': ['states/refundAsynExport-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.refundManage',
            'files': ['states/refundManage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.regionEstablish',
            'files': ['states/regionEstablish-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.regionLearning',
            'files': ['states/regionLearning-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.releaseGoods',
            'files': ['states/releaseGoods-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.reportFormsAsynExport',
            'files': ['states/reportFormsAsynExport-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.requiredPackage',
            'files': ['states/requiredPackage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.restangulartest',
            'files': ['states/restangulartest-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.roleManage',
            'files': ['states/roleManage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.selectCourseCenter',
            'files': ['states/selectCourseCenter-state']
        }, {'reconfig': true, 'name': 'app.admin.states.selling', 'files': ['states/selling-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.siteOpening',
            'files': ['states/siteOpening-state']
        }, {'reconfig': true, 'name': 'app.admin.states.solution', 'files': ['states/solution-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.statisticTaskExport',
            'files': ['states/statisticTaskExport-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.studyStatistic',
            'files': ['states/studyStatistic-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.supplierResource',
            'files': ['states/supplierResource-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.systemProcessTask',
            'files': ['states/systemProcessTask-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.teacherAccountManage',
            'files': ['states/teacherAccountManage-state']
        }, {'reconfig': true, 'name': 'app.admin.states.toBeSales', 'files': ['states/toBeSales-state']}, {
            'reconfig': true,
            'name': 'app.admin.states.trainClassManage',
            'files': ['states/trainClassManage-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.trainingType',
            'files': ['states/trainingType-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.uploadDemo',
            'files': ['states/uploadDemo-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.userAsynExport',
            'files': ['states/userAsynExport-state']
        }, {
            'reconfig': true,
            'name': 'app.admin.states.userManage',
            'files': ['states/userManage-state']
        }, {'reconfig': true, 'name': 'app.admin.states.validator', 'files': ['states/validator-state']}],
        'futureStates': [{
            'module': 'app.admin.states.adminAccountManager',
            'stateName': 'states.adminAccountManager',
            'url': '/adminAccountManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.administratorManage',
            'stateName': 'states.administratorManage',
            'url': '/administratorManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.annualEstablish',
            'stateName': 'states.annualEstablish',
            'url': '/annualEstablish',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.areaPeriodLearnStatistic',
            'stateName': 'states.areaPeriodLearnStatistic',
            'url': '/areaPeriodLearnStatistic',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.certifiedTemplate',
            'stateName': 'states.certifiedTemplate',
            'url': '/certifiedTemplate',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.channelDistribution',
            'stateName': 'states.channelDistribution',
            'url': '/channelDistribution',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.classEstablish',
            'stateName': 'states.classEstablish',
            'url': '/classEstablish',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.classInformation',
            'stateName': 'states.classInformation',
            'url': '/classInformation',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.classLearning',
            'stateName': 'states.classLearning',
            'url': '/classLearning',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.courseCategoryManager',
            'stateName': 'states.courseCategoryManager',
            'url': '/courseCategoryManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.courseChooseStatistic',
            'stateName': 'states.courseChooseStatistic',
            'url': '/courseChooseStatistic',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.courseManager',
            'stateName': 'states.courseManager',
            'url': '/courseManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.coursePackageManager',
            'stateName': 'states.coursePackageManager',
            'url': '/coursePackageManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.coursePoolRuleManager',
            'stateName': 'states.coursePoolRuleManager',
            'url': '/coursePoolRuleManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.courseSelect',
            'stateName': 'states.courseSelect',
            'url': '/courseSelect',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.coursewareAsyn',
            'stateName': 'states.coursewareAsyn',
            'url': '/coursewareAsyn',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.courseWareCategoryManager',
            'stateName': 'states.courseWareCategoryManager',
            'url': '/courseWareCategoryManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.courseWareManager',
            'stateName': 'states.courseWareManager',
            'url': '/courseWareManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.creditStatistics',
            'stateName': 'states.creditStatistics',
            'url': '/creditStatistics',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.defenceFakeLearning',
            'stateName': 'states.defenceFakeLearning',
            'url': '/defenceFakeLearning',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.differentPrice',
            'stateName': 'states.differentPrice',
            'url': '/differentPrice',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.distributionManager',
            'stateName': 'states.distributionManager',
            'url': '/distributionManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.distributorOpenImportTask',
            'stateName': 'states.distributorOpenImportTask',
            'url': '/distributorOpenImportTask',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.distributorOpenManage',
            'stateName': 'states.distributorOpenManage',
            'url': '/distributorOpenManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.distributorOrderManager',
            'stateName': 'states.distributorOrderManager',
            'url': '/distributorOrderManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.employee',
            'stateName': 'states.employee',
            'url': '/employee',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.exam',
            'stateName': 'states.exam',
            'url': '/exam',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.examStatistics',
            'stateName': 'states.examStatistics',
            'url': '/examStatistics',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.falseLearning',
            'stateName': 'states.falseLearning',
            'url': '/falseLearning',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.feedback',
            'stateName': 'states.feedback',
            'url': '/feedback',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.goodsManager',
            'stateName': 'states.goodsManager',
            'url': '/goodsManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.hasnotPopQuestionCourseList',
            'stateName': 'states.hasnotPopQuestionCourseList',
            'url': '/hasnotPopQuestionCourseList',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.home',
            'stateName': 'states.home',
            'url': '/home',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.humanActivation',
            'stateName': 'states.humanActivation',
            'url': '/humanActivation',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.importClassOpen',
            'stateName': 'states.importClassOpen',
            'url': '/importClassOpen',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.importOpenClassTask',
            'stateName': 'states.importOpenClassTask',
            'url': '/importOpenClassTask',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.importStudent',
            'stateName': 'states.importStudent',
            'url': '/importStudent',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.importStudentTask',
            'stateName': 'states.importStudentTask',
            'url': '/importStudentTask',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.infoCategory',
            'stateName': 'states.infoCategory',
            'url': '/infoCategory',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.infoContent',
            'stateName': 'states.infoContent',
            'url': '/infoContent',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.invoiceExport',
            'stateName': 'states.invoiceExport',
            'url': '/invoiceExport',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.invoiceManage',
            'stateName': 'states.invoiceManage',
            'url': '/invoiceManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.invoiceViews',
            'stateName': 'states.invoiceViews',
            'url': '/invoiceViews',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.job',
            'stateName': 'states.job',
            'url': '/job',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.learningTimeStatistic',
            'stateName': 'states.learningTimeStatistic',
            'url': '/learningTimeStatistic',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.logonStatistic',
            'stateName': 'states.logonStatistic',
            'url': '/logonStatistic',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.menu1',
            'stateName': 'states.menu1',
            'url': '/menu1',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.merchant',
            'stateName': 'states.merchant',
            'url': '/merchant',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.messageReply',
            'stateName': 'states.messageReply',
            'url': '/messageReply',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.normal',
            'stateName': 'states.normal',
            'url': '/normal',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.noticeManage',
            'stateName': 'states.noticeManage',
            'url': '/noticeManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.openRecord',
            'stateName': 'states.openRecord',
            'url': '/openRecord',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.orderAsynchExport',
            'stateName': 'states.orderAsynchExport',
            'url': '/orderAsynchExport',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.orderManage',
            'stateName': 'states.orderManage',
            'url': '/orderManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.orgManage',
            'stateName': 'states.orgManage',
            'url': '/orgManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.packageDispatch',
            'stateName': 'states.packageDispatch',
            'url': '/packageDispatch',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.packageExportManager',
            'stateName': 'states.packageExportManager',
            'url': '/packageExportManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.packageImportManager',
            'stateName': 'states.packageImportManager',
            'url': '/packageImportManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.paperClassification',
            'stateName': 'states.paperClassification',
            'url': '/paperClassification',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.paperConfig',
            'stateName': 'states.paperConfig',
            'url': '/paperConfig',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.paymentAccount',
            'stateName': 'states.paymentAccount',
            'url': '/paymentAccount',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.periodSellStatistic',
            'stateName': 'states.periodSellStatistic',
            'url': '/periodSellStatistic',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.personCenter',
            'stateName': 'states.personCenter',
            'url': '/personCenter',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.player',
            'stateName': 'states.player',
            'url': '/player',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.popQuestionManager',
            'stateName': 'states.popQuestionManager',
            'url': '/popQuestionManager',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.practicePaperConfig',
            'stateName': 'states.practicePaperConfig',
            'url': '/practicePaperConfig',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.problemCategory',
            'stateName': 'states.problemCategory',
            'url': '/problemCategory',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.questionImport',
            'stateName': 'states.questionImport',
            'url': '/questionImport',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.questionLibrary',
            'stateName': 'states.questionLibrary',
            'url': '/questionLibrary',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.questionManage',
            'stateName': 'states.questionManage',
            'url': '/questionManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.reconciliationManage',
            'stateName': 'states.reconciliationManage',
            'url': '/reconciliationManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.reconciliationViews',
            'stateName': 'states.reconciliationViews',
            'url': '/reconciliationViews',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.refundAsynExport',
            'stateName': 'states.refundAsynExport',
            'url': '/refundAsynExport',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.refundManage',
            'stateName': 'states.refundManage',
            'url': '/refundManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.regionEstablish',
            'stateName': 'states.regionEstablish',
            'url': '/regionEstablish',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.regionLearning',
            'stateName': 'states.regionLearning',
            'url': '/regionLearning',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.releaseGoods',
            'stateName': 'states.releaseGoods',
            'url': '/releaseGoods',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.reportFormsAsynExport',
            'stateName': 'states.reportFormsAsynExport',
            'url': '/reportFormsAsynExport',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.requiredPackage',
            'stateName': 'states.requiredPackage',
            'url': '/requiredPackage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.restangulartest',
            'stateName': 'states.restangulartest',
            'url': '/restangulartest',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.roleManage',
            'stateName': 'states.roleManage',
            'url': '/roleManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.selectCourseCenter',
            'stateName': 'states.selectCourseCenter',
            'url': '/selectCourseCenter',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.selling',
            'stateName': 'states.selling',
            'url': '/selling',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.siteOpening',
            'stateName': 'states.siteOpening',
            'url': '/siteOpening',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.solution',
            'stateName': 'states.solution',
            'url': '/solution',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.statisticTaskExport',
            'stateName': 'states.statisticTaskExport',
            'url': '/statisticTaskExport',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.studyStatistic',
            'stateName': 'states.studyStatistic',
            'url': '/studyStatistic',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.supplierResource',
            'stateName': 'states.supplierResource',
            'url': '/supplierResource',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.systemProcessTask',
            'stateName': 'states.systemProcessTask',
            'url': '/systemProcessTask',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.teacherAccountManage',
            'stateName': 'states.teacherAccountManage',
            'url': '/teacherAccountManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.toBeSales',
            'stateName': 'states.toBeSales',
            'url': '/toBeSales',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.trainClassManage',
            'stateName': 'states.trainClassManage',
            'url': '/trainClassManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.trainingType',
            'stateName': 'states.trainingType',
            'url': '/trainingType',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.uploadDemo',
            'stateName': 'states.uploadDemo',
            'url': '/uploadDemo',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.userAsynExport',
            'stateName': 'states.userAsynExport',
            'url': '/userAsynExport',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.userManage',
            'stateName': 'states.userManage',
            'url': '/userManage',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.admin.states.validator',
            'stateName': 'states.validator',
            'url': '/validator',
            'type': 'ocLazyLoad'
        }]
    };
});