define(function () {
    'use strict';
    return {
        'modules': [{
            'reconfig': true,
            'name': 'app.center.states.accountSetting',
            'files': ['states/accountSetting-state']
        }, {'reconfig': true, 'name': 'app.center.states.home', 'files': ['states/home-state']}, {
            'reconfig': true,
            'name': 'app.center.states.message',
            'files': ['states/message-state']
        }, {'reconfig': true, 'name': 'app.center.states.myCourse', 'files': ['states/myCourse-state']}, {
            'reconfig': true,
            'name': 'app.center.states.myOrder',
            'files': ['states/myOrder-state']
        }, {
            'reconfig': true,
            'name': 'app.center.states.myRealClass',
            'files': ['states/myRealClass-state']
        }, {
            'reconfig': true,
            'name': 'app.center.states.shoppingCart',
            'files': ['states/shoppingCart-state']
        }, {
            'reconfig': true,
            'name': 'app.center.states.signUpTraining',
            'files': ['states/signUpTraining-state']
        }, {
            'reconfig': true,
            'name': 'app.center.states.signUpTraining.introduction',
            'files': ['states/signUpTraining.introduction-state']
        }, {'reconfig': true, 'name': 'app.center.states.test', 'files': ['states/test-state']}, {
            'reconfig': true,
            'name': 'app.center.states.testResult',
            'files': ['states/testResult-state']
        }, {
            'reconfig': true,
            'name': 'app.center.states.trainingCertificate',
            'files': ['states/trainingCertificate-state']
        }],
        'futureStates': [{
            'module': 'app.center.states.accountSetting',
            'stateName': 'states.accountSetting',
            'url': '/accountSetting',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.home',
            'stateName': 'states.home',
            'url': '/home',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.message',
            'stateName': 'states.message',
            'url': '/message',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.myCourse',
            'stateName': 'states.myCourse',
            'url': '/myCourse',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.myOrder',
            'stateName': 'states.myOrder',
            'url': '/myOrder',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.myRealClass',
            'stateName': 'states.myRealClass',
            'url': '/myRealClass',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.shoppingCart',
            'stateName': 'states.shoppingCart',
            'url': '/shoppingCart',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.signUpTraining',
            'stateName': 'states.signUpTraining',
            'url': '/signUpTraining',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.signUpTraining.introduction',
            'stateName': 'states.signUpTraining.introduction',
            'url': '/signUpTraining.introduction',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.test',
            'stateName': 'states.test',
            'url': '/test',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.testResult',
            'stateName': 'states.testResult',
            'url': '/testResult',
            'type': 'ocLazyLoad'
        }, {
            'module': 'app.center.states.trainingCertificate',
            'stateName': 'states.trainingCertificate',
            'url': '/trainingCertificate',
            'type': 'ocLazyLoad'
        }]
    };
});